FROM debian:latest

ARG compile_cores=8

#update system
RUN apt-get --allow-releaseinfo-change update
RUN DEBIAN_FRONTEND=noninteractive && apt-get --yes update && apt-get --yes upgrade
RUN DEBIAN_FRONTEND=noninteractive && apt-get --yes install git sudo bash wget apt-utils xz-utils python3 python3-pip

ARG NB_USER=usr
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}
WORKDIR ${HOME}

#clone the install scripts and run them
#RUN git clone git@github.com:openmsr/openmc_install_scripts.git
#this is done step by step to avoid invalidating the docker cache.
#COPY OpenMSR/openmc_install_scripts/Debian11/nuclear_data-install.sh .
#RUN ./nuclear_data-install.sh
 
COPY OpenMSR/openmc_install_scripts/Debian11/embree-install.sh .
RUN ./embree-install.sh "$compile_cores"

COPY OpenMSR/openmc_install_scripts/Debian11/moab-install.sh .
RUN ./moab-install.sh "$compile_cores"

COPY OpenMSR/openmc_install_scripts/Debian11/double_down-install.sh .
RUN ./double_down-install.sh "$compile_cores"

COPY OpenMSR/openmc_install_scripts/Debian11/dagmc-install.sh .
RUN ./dagmc-install.sh "$compile_cores"

COPY OpenMSR/openmc_install_scripts/Debian11/openmc-install.sh .
RUN ./openmc-install.sh "$compile_cores"

#clean up a bit
RUN rm *-install.sh
RUN rm *-install.sh.done
#RUN rm $HOME/openmc/nuclear_data/*.xz
#RUN rm $HOME/openmc/nuclear_data/*-install.sh.done

RUN mkdir msre
COPY msre_simple.h5m msre/
COPY msre_control*.h5m msre/
COPY msre_*.py msre/

ENV OPENMC_CROSS_SECTIONS=/home/${NB_USER}/openmc/nuclear_data/mcnp_endfb71/cross_sections.xml
